---
title: 'Desafio do Titanic do Kaggle: Uma abordagem didática na exploração e preparação
  dos dados para análise preditiva'
author: acsjunior
date: '2020-08-09'
slug: []
banner: img/banners/titanic.jpg
categories:
  - tutoriais
tags:
  - linguagem r
  - data wrangling
  - validação cruzada
  - missing data
  - medium
---

O [Kaggle](https://www.kaggle.com/), de forma resumida, é uma plataforma que hospeda competições de ciência de dados, famosa entre profissionais e entusiastas da área. Entre as diversas competições disponíveis ao público, o desafio do Titanic provavelmente seja o mais popular entre os iniciantes no mundo dos dados.

A competição funciona da seguinte forma: o Kaggle fornece os dados sobre os passageiros do RMS Titanic, o famoso transatlântico britânico naufragado em 1912. Entre dados como sexo, preço da tarifa, porto de embarque e etc., há uma variável que indica se o passageiro sobreviveu ou não ao naufrágio. No entanto, parte dos passageiros não possui tal informação e a partir daí o competidor entra em ação através de uma análise preditiva para tentar adivinhar quais passageiros sobreviveram ao desastre.
A proposta deste artigo é apresentar aos ̶m̶a̶r̶i̶n̶h̶e̶i̶r̶o̶s̶ cientistas de dados de primeira viagem uma abordagem didática, através da linguagem R, no processo de exploração e preparação dos dados, incluindo a criação de novas variáveis e a imputação de dados ausentes, de modo que ao término do processo tenhamos um conjunto de dados adequado para modelagem preditiva.

*[Clique aqui](https://juniorssz.medium.com/desafio-do-titanic-do-kaggle-uma-abordagem-didática-na-exploração-e-preparação-dos-dados-ec5988d2d33) para acessar o artigo completo publicado no [Medium](https://medium.com/).*
